#pragma once

// Included from class UI's private section (200-line split).

    void init();
    void load_config();
    void register_actions();
    void register_workbench_actions();
    void register_nav_actions();
    void resize();
    void render();
    void handle_inputs();
    void insert_focused_utf8(std::string_view utf8);
    bool dispatch_resolved(int key, InputContext ctx);
    bool dispatch_token(KeyToken tok, InputContext ctx);
    void handle_overlay_input(int ch);
    void handle_sidebar_input(int ch);
    void update_statusbar_mode();
    void update_cursor_visibility();
    void execute_command();
    void sync_active_tab();
    bool close_active_tab(bool force);
    void return_to_normal();
    void open_save_confirm(ConfirmIntent intent);
    void resolve_save_confirm(ConfirmChoice choice);
    bool save_active_buffer();
    void finish_close_or_quit(ConfirmIntent intent, bool force);
    void open_sidebar_prompt(PromptIntent intent);
    void resolve_sidebar_prompt();
    void open_delete_confirm();
    void resolve_delete_confirm(ConfirmChoice choice);
    void toggle_terminal();
    void open_terminal(bool focus_terminal = true);
    void close_terminal();
    void open_search_view(bool focus_search = true);
    void open_explorer_view(bool focus_explorer = true);
    void apply_replace_all();
    int effective_sidebar_width() const;
    std::string when_context() const;
    void set_sidebar_visible(bool visible);
    void toggle_sidebar();
    void open_sidebar(bool focus_sidebar = true);
    void close_sidebar();
    void open_file_search();
    void close_file_search(bool open_selected);
    void open_buffer_search();
    void close_buffer_search(bool open_selected);
    void apply_workspace_root(const fs::path &hint, bool announce = true);
    void open_workspace_prompt();
    void remap_buffer_path(const fs::path &from, const fs::path &to);
    void close_buffers_under(const fs::path &path);
    void note_opened_file(const fs::path &path);
    void trigger_completion();
    void close_completion(bool accept);
    void poll_completion_result();
    void sync_scm_ui();
    void refresh_scm(const fs::path &hint);
    void sync_scm_diff();
    void scm_stage_active();
    void scm_unstage_active();
    void scm_discard_active_confirm();
    void scm_show_diff_summary();
    void resolve_discard_confirm(ConfirmChoice choice);
    void sync_fs_watches();
    void poll_fs_events();
    void sync_messages_echo();

    SessionState capture_session_state() const;
    void save_session();
    bool restore_session_if_available(bool allow_replace_tabs);
    void queue_recovery_prompts();
    void open_recovery_confirm();
    void resolve_recovery_confirm(ConfirmChoice choice);
    void tick_recovery_snapshots();
    void clear_recovery_for_buffer(const Buffer &buffer);

    void goto_lsp_location(const LspLocation &loc);
    void apply_lsp_workspace_edit(LspWorkspaceEdit edit);
    void open_lsp_locations(std::string title, std::vector<LspLocation> locs);
    void open_lsp_symbols(std::string title, std::vector<LspSymbol> syms);
    void open_lsp_actions(std::vector<LspCodeAction> actions);
    void close_lsp_picker(bool accept);
    void poll_lsp_results();
    void request_lsp_definition();
    void request_lsp_declaration();
    void request_lsp_type_definition();
    void request_lsp_references();
    void request_lsp_document_symbols();
    void request_lsp_workspace_symbols_prompt();
    void request_lsp_rename_prompt();
    void request_lsp_code_actions();
    fs::path project_root() const;
    fs::path find_workspace_root(const fs::path &hint) const;
